name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Select a version:'
        required: true
        options:
          - patch
          - minor
          - major
          - prerelease
          - premajor
          - preminor
          - prepatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: ${{github.ref_name}}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Git config
        run: |
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}@users.noreply.github.com
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Release to GitHub/NPM
        run: yarn release-it ${{ github.event.inputs.version }} --ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
